-- Create table for global admin-controlled settings
CREATE TABLE IF NOT EXISTS public.clipbeam_admin_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lockdown_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  announcement_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  announcement_title TEXT,
  announcement_body TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Ensure there is always at most one row used by the app
CREATE UNIQUE INDEX IF NOT EXISTS clipbeam_admin_settings_singleton_idx ON public.clipbeam_admin_settings ((true));

-- Enable RLS and restrict access to backend only
ALTER TABLE public.clipbeam_admin_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role full access admin settings" 
ON public.clipbeam_admin_settings
AS PERMISSIVE
FOR ALL
TO public
USING (auth.role() = 'service_role')
WITH CHECK (auth.role() = 'service_role');

-- Seed a default row if none exists
INSERT INTO public.clipbeam_admin_settings (lockdown_enabled, announcement_enabled, announcement_title, announcement_body)
SELECT FALSE, FALSE, 'Support this project', 'Pasto is a side project. Consider donating or leaving feedback if you find it useful.'
WHERE NOT EXISTS (SELECT 1 FROM public.clipbeam_admin_settings);